package cz.tw.proxymanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TwAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTwAccountAllPropertiesEquals(TwAccount expected, TwAccount actual) {
        assertTwAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertTwAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTwAccountAllUpdatablePropertiesEquals(TwAccount expected, TwAccount actual) {
        assertTwAccountUpdatableFieldsEquals(expected, actual);
        assertTwAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTwAccountAutoGeneratedPropertiesEquals(TwAccount expected, TwAccount actual) {
        assertThat(expected)
            .as("Verify TwAccount auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTwAccountUpdatableFieldsEquals(TwAccount expected, TwAccount actual) {
        assertThat(expected)
            .as("Verify TwAccount relevant properties")
            .satisfies(e -> assertThat(e.getUsername()).as("check username").isEqualTo(actual.getUsername()))
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTwAccountUpdatableRelationshipsEquals(TwAccount expected, TwAccount actual) {
        assertThat(expected)
            .as("Verify TwAccount relationships")
            .satisfies(e -> assertThat(e.getProxy()).as("check proxy").isEqualTo(actual.getProxy()));
    }
}
